### ISSUE TITLE
Configuring REST handlers?

### ISSUE THREAD

**Issue by kokujin** [feathersjs/feathers-demos#11]
Feathers can handle REST request out of the box. This is great. I read the docs on hooks, what I missed was the standard way of configuring handlers, not during the before or after lifecycles.

These are where one puts the lifecycle handlers, hooks/index.js, where does one place the normal handlers? There are no controllers to modify to handle, for example a "DELETE".
`````
exports.before = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

exports.after = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

`````

Thanks

**Comment by daffl** [comment]
You can register custom Express middleware before or after a server as described at http://docs.feathersjs.com/middleware/express.html#custom-service-middleware and then check `req.method` for the HTTP method you want to hook into.

**Comment by kokujin** [comment]
Why was this issue closed? Maybe I wasnt clear.

1. I can find the docs for Express compatible middleware.
2. I can find the docs for hooks and the lifecycles.

What I cant find are the docs to modify or customize the default Feathers REST handlers.

If I generate an app using the CLI, I ca fire request at the app using Postman for example, this is fine, but where are these REST handlers defined? What is the preferred Feathers way to modify them?
