### ISSUE TITLE
Authentication demo oath2 contains "full" code in both index.js and apps.js

### ISSUE THREAD

**Issue by stjarnstrom** [feathersjs/feathers-demos#13]
The index.js code is broken (albeit, not referenced at all). It should be either removed or fixed in some way.

**Comment by ekryski** [comment]
@stjarnstrom not sure I follow. Can you elaborate? I'm not sure what the actual issue is.

**Comment by ekryski** [comment]
nvm. I got it. That file accidentally got committed and it shouldn't have. Thanks! 😄
