### ISSUE TITLE
How to control middleware access?

### ISSUE THREAD

**Issue by bahmutov** [feathersjs/feathers-demos#18]
Hi!

After successful oauth login, how do I check if the user is authenticated for simple `app.get(...)` middleware (not service)? For example after line https://github.com/feathersjs/feathers-demos/blob/master/examples/authentication/oauth2/app.js#L35

I would like to write `isAuthenticated` that uses oauth2 GithubStrategy result only to send the secret HTML file to authenticated users.

```js
app.get('/secret', isAuthenticated, function(req, res){
    res.sendFile(path.resolve(__dirname, 'public', 'secret.html'));
});
```

**Comment by ekryski** [comment]
Fixes are coming to resolve this in the new version of feathers-authentication. You can actually try the 0.8-beta now which includes an `isAuthenticated` middleware.
